config/routes.rb
Hexedguild::Application.routes.draw do

	root to: 'static_pages#home'

	match "help", to: "static_pages#help"
	match "contact", to: "static_pages#contact"
	match "about", to: "static_pages#about"

	match "wow", to: "static_pages#wow"
	match "tera", to: "static_pages#tera"

	match "apply", to: "users#new"
	match "signin", to: "sessions#new"
	match "signout", to: "sessions#destroy", via: :delete

	match "admin", to: "users#admin", via: :get, as: "admin"
	match "admin", to: "users#admin_login", via: :post, as: "admin_login"

	match "members(.:format)", to: "users#index", via: :get, as: "members"
	match "members(.:format)", to: "users#create", via: :post
	match "members/new(.:format)", to: "users#new", via: :get, as: "new_member"
	match ":character/edit(.:format)", to: "users#edit", via: :get, as: "edit_member"
	match ":character(.:format)", to: "users#show", via: :get, as: "member"
	match ":character(.:format)", to: "users#update", via: :put
	match ":character(.:format)", to: "users#destroy", via: :delete
	match ":character/confirm(.:format)", to: "users#confirm", via: :put, as: "confirm_member"

	resources :users
	resources :wow_toons, only: [:create, :destroy]
	resources :tera_toons, only: [:create, :destroy]
	resources :sessions, only: [:new, :create, :destroy]
	resources :articles, only: [:create, :destroy]

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
		@article = current_user.articles.build if signed_in?
		@announcement = Article.where(announcement: true).limit(1)
		@articles = Article.where(announcement: false).limit(10)
  end

	def wow
		@announcement = Article.where(announcement: true).where(wow: true).limit(1)
		@articles = Article.where(announcement: false).where(wow: true).paginate(page: params[:page])
	end

	def tera
		@announcement = Article.where(announcement: true).where(tera: true).limit(1)
		@articles = Article.where(announcement: false).where(tera: true).paginate(page: params[:page])
	end

  def help
  end

  def contact
  end

	def about
	end

	def admin
	end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.erb
<% provide(:title, "About Hexed") %>
<% provide(:game, 'combined') %>
<h1>About Hexed</h1>
<p>
Hexed has been around for 6+ years and now spans two full worlds 
in the form of World of Warcraft and Tera.</br><br/>
We are a very active guild and are always looking for new members 
to help fill our ranks. Please apply in game or wait until 
the application process has been created here.<br/><br/>Thank 
you for visiting.
</p>
<h4>WoW: Korialstraz</h4>
<p>
	<ul>
		<li>Leader: Malaron</li>
	</ul>
</p>
<h4>TERA: Basilisk Crag</h4>
<p>
	<ul>
		<li>Leader: Trydle</li>
	</ul>
</p>
<h4>Vent</h4>
<p>
	<ul>
		<li>IP: 63.247.87.4</li>
		<li>Port: 3030</li>
		<li>Password: Ask Malaron or Stereg for an account for WoW, or Trydle for TERA</li>
	</ul>
</p>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>
<% provide(:game, 'combined') %>
<h1>Contact</h1>
<p>Work In Progress</p>

app/views/static_pages/help.html.erb
<% provide(:title, 'Help') %>
<h1>Help</h1>
<p>Work in Progress</p>

app/views/static_pages/home.html.erb
<% provide(:game, 'combined') %>
<% if signed_in? %>
	<div class='row'>
		<aside class='span4'>
			<section>
				<%= render 'shared/user_info' %>
			</section>
			<% if current_user.member %>
			<section>
				<%= render 'shared/article_form' %>
			</section>
			<% end %>
		</aside>
		<div class='span6 offset1'>
			<ol class='articles'>
				<%= render @announcement, format: :feed %>
			</ol>
			<ol class='articles'>
				<%= render @articles, format: :feed %>
			</ol>
		</div>
	</div>
<% else %>
	<div class='center villain-unit'>
		<h1>Hexed Guild</h1>
	
		<h2>
			The site for all things Hexed.
		</h2>
	
		<%= link_to "Apply now!", apply_path, class: "btn btn-large btn-primary" %>
	</div>
<% end %>

app/views/static_pages/tera.html.erb
<% provide(:title, "TERA") %>
<% provide(:game, 'tera') %>
<h1>TERA</h1>
<%= render 'shared/view_articles' %>

app/views/static_pages/wow.html.erb
<% provide(:title, "WoW") %>
<% provide(:game, 'wow') %>
<h1>WoW</h1>
<%= render 'shared/view_articles' %>