config/routes.rb
Hexedguild::Application.routes.draw do

	root to: 'static_pages#home'

	match "help", to: "static_pages#help"
	match "contact", to: "static_pages#contact"
	match "about", to: "static_pages#about"

	match "wow", to: "static_pages#wow"
	match "tera", to: "static_pages#tera"

	match "apply", to: "users#new"
	match "signin", to: "sessions#new"
	match "signout", to: "sessions#destroy", via: :delete

	match "admin", to: "users#admin", via: :get, as: "admin"
	match "admin", to: "users#admin_login", via: :post, as: "admin_login"

	match "members(.:format)", to: "users#index", via: :get, as: "members"
	match "members(.:format)", to: "users#create", via: :post
	match "members/new(.:format)", to: "users#new", via: :get, as: "new_member"
	match ":character/edit(.:format)", to: "users#edit", via: :get, as: "edit_member"
	match ":character(.:format)", to: "users#show", via: :get, as: "member"
	match ":character(.:format)", to: "users#update", via: :put
	match ":character(.:format)", to: "users#destroy", via: :delete
	match ":character/confirm(.:format)", to: "users#confirm", via: :put, as: "confirm_member"

	resources :users
	resources :wow_toons, only: [:create, :destroy]
	resources :tera_toons, only: [:create, :destroy]
	resources :sessions, only: [:new, :create, :destroy]
	resources :articles, only: [:create, :destroy]

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer         not null, primary key
#  name            :string(255)
#  character       :string(255)
#  email           :string(255)
#  tera            :boolean
#  wow             :boolean
#  created_at      :datetime        not null
#  updated_at      :datetime        not null
#  password_digest :string(255)
#  remember_token  :string(255)
#  member          :boolean         default(FALSE)
#  admin           :boolean         default(FALSE)
#  apply           :string(255)
#

class User < ActiveRecord::Base
  attr_accessible :character, :email, :name, :tera, :wow, :apply, :password, :password_confirmation
	has_secure_password

	has_many :wow_toons, dependent: :destroy
	has_many :tera_toons, dependent: :destroy
	has_many :articles, dependent: :destroy

	before_save { |user| user.email = email.downcase }
	before_save :create_remember_token

	validates :name,
		presence: true,
		length: { maximum: 50 }
		
	
	validates :character,
		presence: true,
		length: { maximum: 16 },
		exclusion: { in: %w( admin signin signup user users apply about contact members forum tera wow home signout) }
	
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	
	validates :email,
		presence: true,
		format: { with: VALID_EMAIL_REGEX },
		uniqueness: { case_sensitive: false }

	validates :password,
		presence: true,
		length: { minimum: 6 }
	
	validates :password_confirmation,
		presence: true

	validates :apply, presence: true, length: { maximum: 500 }

	validates :wow, presence: { unless: "tera", message: "Must be part of WoW or TERA" }

	private
		
		def create_remember_token
			self.remember_token = SecureRandom.urlsafe_base64
		end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_filter :signed_in_user, only: [:index, :edit, :update, :show, :destroy, :admin]  
	before_filter :correct_user, only: [:edit, :update]
	before_filter :member_user, only: :show
	before_filter :admin_user, only: :destroy

	def new
		@user = User.new
  end

	def create
		@user = User.new(params[:user])
		if @user.save
			sign_in @user
			flash[:success] = "Welcome to Hexed!"
			redirect_to member_path(@user.character)
		else
			render 'new'
		end
	end

	def index
		@users = User.paginate(page: params[:page])
	end

	def show
		@user = get_user(params)
		if @user.nil?
			flash[:notice] = "User not found"
			redirect_to root_path
		else
			@wow_toon = current_user.wow_toons.build if signed_in?
			@wow_toons = @user.wow_toons
			@tera_toon = current_user.tera_toons.build if signed_in?
			@tera_toons = @user.tera_toons
			@articles = @user.articles.paginate(page: params[:page], per_page: 20)
		end
	end

	def edit
	end

	def update
		if @user.update_attributes(params[:user])
			flash[:success] = "Profile Updated"
			sign_in @user
			redirect_to member_path(@user.character)
		else
			render 'edit'
		end
	end

	def confirm
		@user = get_user(params)
		if @user == current_user
			@relog = true
		end
		if @user.toggle!(:member)
			flash[:success] = "#{@user.character} Confirmed!"
		else
			flash[:error] = "Error Confirming #{@user.character}"
		end
		if @relog
			sign_out
			sign_in @user
		end
		redirect_to members_path
	end

	def admin
	end

	def admin_login
		if params[:password] == "1337guildm45732"
			@user = current_user
			if not @user.admin and @user.toggle!(:admin)
				sign_out
				sign_in @user
				flash[:success] = "This account is now an admin account"
				redirect_to @user
			else
				if @user.admin
					flash[:error] = "User is already an admin"
					redirect_to @user
				else
					flash[:error] = "Error logging in as an admin"
					redirect_to root_path
				end
			end
		else
			flash[:error] = "Invalid attempt at access. Your account will be reported."
			# add a report function at some point
			redirect_to root_path
		end
	end

	def destroy
		User.find(params[:id]).destroy
		flash[:success] = "User destroyed."
		redirect_to members_path
	end
end

app/helpers/users_helper.rb
module UsersHelper

	def user_game(user)
		if (user.wow and user.tera) or (not user.wow and not user.tera)
			"combined"
		else
			if user.wow
				"wow"
			else
				"tera"
			end
		end
	end
end

app/views/users/_user.html.erb
<li class='row'>
	<% if user.wow %>
		<div class='span1'>
			<%= image_tag('wow_icon.png') %>
		</div>
		<% if user.tera %>
			<div class='span1'>
				<%= image_tag('tera_icon.jpg') %>
			</div>
			<h4 class='span2'>
				<%= user.character %>
			</h4>
		<% else %>
			<h4 class='span2 offset1'>
				<%= user.character %>
			</h4>
		<% end %>
	<% else %>
		<% if user.tera %>
			<div class='span1 offset1'>
				<%= image_tag('tera_icon.jpg') %>
			</div>
			<h4 class='span2'>
				<%= user.character %>
			</h4>
		<% else %>
			<h4 class='span2 offset2'>
				<%= user.character %>
			</h4>
		<% end %>
	<% end %>
	<% if current_user.member? or current_user?(user) %>
		<%= link_to "View", member_path(user.character), class: 'span1' %>
	<% end %>
	<% if current_user.admin? %>
		<% if not user.member? %>
			<%= link_to "Confirm", confirm_member_path(user.character), method: :put, confirm: "You Sure?", class: 'span1' %>
		<% end %>
		<% if !current_user?(user) %>
			<%= link_to "Delete", user, method: :delete, confirm: "You Sure?", class: 'span1' %>
		<% end %>
	<% end %>
</li>

app/views/users/admin.html.erb
<% provide(:title, 'Admin Login') %>
<% provide(:game, 'combined') %>
<h1>Admin Signin</h1>
<div class='row'>
	<div class='span6 offset3'>
		<%= form_tag admin_login_path, method: :post do %>
			<%= label_tag "Password" %>
			<%= password_field_tag :password %>
			<%= submit_tag "Submit" %>
		<% end %>
	</div>
</div> 

app/views/users/edit.html.erb
<% provide(:title, "Edit User") %>
<% provide(:game, user_game(@user)) %>
<h1>Update your profile</h1>
<div class='row'>
	<div class='span6 offset3'>
		<%= simple_form_for(@user) do |f| %>
			<%= render 'shared/error_messages', object: f.object %>

			<%= f.input :name %>
			<%= f.input :character %>
			<%= f.input :email %>
			<%= f.input :password %>
			<%= f.input :password_confirmation, label: "Confirmation" %>

			<%= f.submit "Save Changes", class: 'btn btn-large btn-primary' %>
		<% end %>
	</div>
</div>

app/views/users/index.html.erb
<% provide(:title, "All Members") %>
<% provide(:game, 'combined') %>
<h1>All Members</h1>

<%= will_paginate %>

<ul class="members">
	<%= render @users %>
</ul>

<%= will_paginate %>

app/views/users/new.html.erb
<% provide(:title, "Apply") %>
<% provide(:game, 'combined') %>
<h1>Application</h1>
<div class='row'>
	<div class='span6 offset3'>
		<%= form_for @user do |f| %>
			<%= render 'shared/error_messages', object: f.object %>
			<%= f.label :name %>
			<%= f.text_field :name %>
			<%= f.label :character %>
			<%= f.text_field :character %>
			<%= f.label :email %>
			<%= f.email_field :email %>
			<%= f.label :wow %>
			<%= f.check_box :wow %>
			<%= f.label :tera %>
			<%= f.check_box :tera %>
			<%= f.label :apply %>
			<%= f.text_area :apply %>
			<%= f.label :password %>
			<%= f.password_field :password %>
			<%= f.label :password_confirmation %>
			<%= f.password_field :password_confirmation %>
			<%= f.submit "Apply", class: "btn btn-large btn-primary" %>
		<% end %>
	</div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.character) %>
<% provide(:game, user_game(@user)) %>
<div class='row'>
	<aside class='span2'>
		<section>
			<h1>
				<%= @user.character %>
			</h1>
			<br/>
			<h4>
				<% if @user.member %>
					Guildy
				<% else %>
					Recruit
				<% end %>
			</h4>
			<br/>
			<% if current_user.admin? %>
				<h4>Application</h4>
				<p>
					<%= @user.apply %>
				</p>
			<% end %>
		</section>
	</aside>
	<div class='span10'>
		<div class= 'row toons'>
			<div class='span4 offset1'>
				<h4>WoW Toons</h4>
				<% if @wow_toons.any? %>
					<ul>
						<% @wow_toons.each do |wtoon| %>
							<li>
								<%= wtoon.name %>
								<% if @user == current_user %>
									<%= link_to 'Delete', wtoon, method: :delete, confirm: "Are you sure?" %>
								<% end %>
							</li>
						<% end %>
					</ul>
				<% end %>
				<% if @user == current_user %>
					<%= form_for @wow_toon do |wf| %>
						<%= wf.label 'New Toon' %>
						<%= wf.text_field :name %>
						<%= wf.submit 'Create' %>
					<% end %>
				<% end %>
			</div>
			<div class='span4 offset1'>
				<h4>TERA Toons</h4>
				<% if @tera_toons.any? %>
					<ul>
						<% @tera_toons.each do |ttoon| %>
							<li>
								<%= ttoon.name %>
								<% if @user == current_user %>
									<%= link_to 'Delete', ttoon, method: :delete, confirm: "Are you sure?" %>
								<% end %>
							</li>
						<% end %>
					</ul>
				<% end %>
				<% if @user == current_user %>
					<%= form_for @tera_toon do |tf| %>
						<%= tf.label 'New Toon' %>
						<%= tf.text_field :name %>
						<%= tf.submit 'Create' %>
					<% end %>
				<% end %>
			</div>
		</div>
	</div>
</div>
<% if @user.articles.any? %>
	<h3>Articles <%= @user.articles.count %></h3>
	<%= render 'shared/view_articles' %>
<% end %>