config/routes.rb
Hexedguild::Application.routes.draw do

	root to: 'static_pages#home'

	match "help", to: "static_pages#help"
	match "contact", to: "static_pages#contact"
	match "about", to: "static_pages#about"

	match "wow", to: "static_pages#wow"
	match "tera", to: "static_pages#tera"

	match "apply", to: "users#new"
	match "signin", to: "sessions#new"
	match "signout", to: "sessions#destroy", via: :delete

	match "admin", to: "users#admin", via: :get, as: "admin"
	match "admin", to: "users#admin_login", via: :post, as: "admin_login"

	match "members(.:format)", to: "users#index", via: :get, as: "members"
	match "members(.:format)", to: "users#create", via: :post
	match "members/new(.:format)", to: "users#new", via: :get, as: "new_member"
	match ":character/edit(.:format)", to: "users#edit", via: :get, as: "edit_member"
	match ":character(.:format)", to: "users#show", via: :get, as: "member"
	match ":character(.:format)", to: "users#update", via: :put
	match ":character(.:format)", to: "users#destroy", via: :delete
	match ":character/confirm(.:format)", to: "users#confirm", via: :put, as: "confirm_member"

	resources :users
	resources :wow_toons, only: [:create, :destroy]
	resources :tera_toons, only: [:create, :destroy]
	resources :sessions, only: [:new, :create, :destroy]
	resources :articles, only: [:create, :destroy]

end

app/views/layouts/_footer.html.erb
<footer class='footer'>
	<small>
		Site based on
		<a href="http://railstutorial.org/">Rails Tutorial</a>
		by Michael Hartl
	</small>
	<nav>
		<ul>
			<li><%= link_to "About Hexed", about_path %></li>
			<li><%= link_to "Contact", contact_path %></li>
		</ul>
	</nav>
</footer>

app/views/layouts/_header.html.erb
<header class='navbar navbar-fixed-top'>
	<div class='navbar-inner'>
		<div class='container'>
			<%= link_to "Hexed", root_path, id: "logo" %>
			<nav>
				<ul class="nav pull-right">
					<li><%= link_to "Home", root_path %></li>
					<li><%= link_to "WoW", wow_path %></li>
					<li><%= link_to "TERA", tera_path %></li>
					<li><%= link_to "Forum", "#" %></li>
					<% if signed_in? %>
						<li><%= link_to "Members", members_path %></li>
						<li id='fat-menu' class='dropdown'>
							<a href="#" class='dropdown-toggle' data-toggle='dropdown'>
								Account <b class='caret'></b>
							</a>
							<ul class='dropdown-menu'>
								<li><%= link_to "Profile", member_path(current_user.character) %></li>
								<li><%= link_to "Settings", edit_member_path(current_user.character) %></li>
								<li class='divider'></li>
								<li>
									<%= link_to "Sign Out", signout_path, method: "delete" %>
								</li>
							</ul>
						</li>
					<% else %>
						<li><%= link_to "Sign In", signin_path %></li>
					<% end %>
				</ul>
			</nav>
		</div>
	</div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
	<%= render 'layouts/shim' %>
</head>
<body>
	<div class="page <%= yield(:game) %>">
		<%= render 'layouts/header' %>
		<div class='container'>
			<% flash.each do |key, value| %>
				<%= content_tag(:div, value, class: "alert alert-#{key}") %>
			<% end %>
			<%= yield %>
			<%= debug(params) if Rails.env.development? %>
		</div>
		<%= render 'layouts/footer' %>
	</div>
</body>
</html>